In [1]:
import torch
import torch.nn
import numpy as np

In [17]:
lst1 = [[123,117,91],[201,195,217],[81, 77, 101]]
type(lst1)


list

In [4]:
arr1 = np.array(lst1)
print(type(arr1))

<class 'numpy.ndarray'>


t1 = torch.tensor(lst1)
t2 = torch.tensor(arr1)
t3 = torch.from_numpy(arr1)

print(type(t1))
print(t1.shape)


In [6]:
t1

tensor([[123, 117,  91],
        [201, 195, 217],
        [ 81,  77, 101]])

In [10]:
print(t1.shape)

torch.Size([3, 3])


In [10]:
torch.Size([3, 3])

torch.Size([3, 3])

In [12]:
print(t1.dtype)

torch.int64


`torch.numel` = number of elements

In [13]:
print(torch.numel(t2))

9


In [14]:
t1

tensor([[123, 117,  91],
        [201, 195, 217],
        [ 81,  77, 101]])

In [15]:
t2

tensor([[123, 117,  91],
        [201, 195, 217],
        [ 81,  77, 101]])

Two ways to make tensors: from `list` and from `np` array

In [16]:
t1 == t2

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

### Creating torch tensors

Create a 3-dimensional tensor with 12 rows and 12 cols

In [20]:
t4 = torch.zeros(size = (3, 12, 12))
print(t4)

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

Create 2 tensors with 4 rows and cols with 1s 

In [21]:
t5 = torch.ones(size=(2,4,4))
print(t5)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


Create a 1 dimension tensor with a range of values starting at 10 and ending before 100 by 5

In [22]:
t6 = torch.arange(start=10, end=100, step=5)
print(t6)

tensor([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])


### Reshaping Tensors

Create 1-d tensor of 32 ones

In [24]:
arr2 = np.ones(32)
t17 = torch.tensor(arr2)
print(t17)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=torch.float64)


reshape to 2-d array with 4 rows and 4 cols

In [28]:
t18 = torch.reshape(t17, (2, 4, 4))
print(t18)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64)


Use `-1` if the dimension is unknown 

In [30]:
t19 = torch.reshape(t17, (-1, 4, 4))
t19

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]], dtype=torch.float64)

In [32]:
t20 = torch.reshape(t17, (4, 4, -1))
print(t20)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.],
         [1., 1.]]], dtype=torch.float64)


`torch.flatten` will turn any tensor into a 1-d tensor

In [33]:
t21 = torch.flatten(t20)
print(t21)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       dtype=torch.float64)


`view()` method can show tensor with a particular dimension

In [36]:
t22 = t17.view((2,16))
print(t22)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],
       dtype=torch.float64)


### Indexing tensors

- Indexing tensors starts at 0
- `:` is used for ranges
- last index not included
- a `colon` by itself selects all elements in that dimension

In [37]:
t23 = torch.randint(low=0, high=256, size = (8,8))
print(t23)

tensor([[ 38,  71,   2, 186,  55, 208, 207,  74],
        [167, 122,  48,  71, 120,  72, 172, 107],
        [ 36,  41, 117, 234,  31, 107, 220, 159],
        [  8,   5, 156, 239, 152, 171,  16, 222],
        [ 49, 105,  67,  29,  13, 233, 198, 167],
        [147,  52, 245,  14,  14, 183, 113,  68],
        [208, 229,  39, 171, 175, 144, 133, 138],
        [219, 207,  83, 166, 100, 155, 225, 207]])


select all the rows, and 0-4 of the columns

In [40]:
t24 = t23[:,0:4]
print(t24)

tensor([[ 38,  71,   2, 186],
        [167, 122,  48,  71],
        [ 36,  41, 117, 234],
        [  8,   5, 156, 239],
        [ 49, 105,  67,  29],
        [147,  52, 245,  14],
        [208, 229,  39, 171],
        [219, 207,  83, 166]])


select 0-4 of the rows and all the cols

In [41]:
t25 = t23[0:4,:]
print(t25)

tensor([[ 38,  71,   2, 186,  55, 208, 207,  74],
        [167, 122,  48,  71, 120,  72, 172, 107],
        [ 36,  41, 117, 234,  31, 107, 220, 159],
        [  8,   5, 156, 239, 152, 171,  16, 222]])


Squeeze and Unsqueeze

In [42]:
t29 = torch.ones((1,4,4))
print(t29.shape)

torch.Size([1, 4, 4])


In [44]:
t29

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [43]:
t30 = t29.squeeze()
print(t30.shape)

torch.Size([4, 4])


In [45]:
t30

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])